name: awsgoo
services:
  nginx-proxy:
    build: ../../docker_file/nginx_compose
    ports:
      - "9889:80"
     
    depends_on:
      - myblog
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  scp-proxy:
    build: ../../../sc-gateway
    # image: jiminu/sc-gateway:0.3.0
    ports:
      - "9000:9000"
    depends_on:
      - myblog
      - eureka
    environment:
      - HELLO_SVC_URI=http://awsgoo-myblog-1:8080
      - EUREKA_SVC_URI=http://awsgoo-eureka-1:9090

  myblog:
    image: jiminu/simple-spring:0.1.2
    ports:
      - "8765:8080"
    deploy:
      mode: replicated
      replicas: 1 
      resources: 
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose: 
      - "8080"
    environment:
      - VIRTUAL_HOST=aws.google.com,aws.abcdef.com
      - VIRTUAL_PORT=8080

  eureka:
    build: ../../../scloud/eureka-serv
    ports:
      - "9999:9090"

  user-service:
    build: ../../../scloud/user-service
    depends_on:
      - eureka

