name: awsgoo
services:
  nginx-proxy:
    build: ../../docker_file/nginx_compose
    ports:
      - "9889:80"
     
    depends_on:
      - myblog
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  scp-proxy:
    build: ../../../sc-gateway
    # image: jiminu/sc-gateway:0.3.0
    ports:
      - "9991:9000"
    depends_on:
      - myblog
      - sc-eureka
    environment:
      - HELLO_SVC_URI=http://awsgoo-myblog-1:8080
        #- EUREKA_SVC_URI=http://sc-eureka:9090
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:9090/eureka

  myblog:
    image: jiminu/simple-spring:0.1.2-amd
    ports:
      - "8765:8080"
    deploy:
      mode: replicated
      replicas: 1 
      resources: 
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose: 
      - "8080"
    environment:
      - VIRTUAL_HOST=aws.google.com,aws.abcdef.com
      - VIRTUAL_PORT=8080
      - CPU_STRESS_NUMBER=500

  sc-eureka:
    build: ../../../scloud/eureka-serv
    container_name: sc-eureka
    ports:
      - "9999:9090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:9090/eureka

  user-service:
    build: ../../../scloud/user-service
    depends_on:
      - sc-eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:9090/eureka
      - SERVER_PORT=9001
    deploy:
      mode: replicated
      replicas: 2
      resources: 
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.01'
          memory: 20M

  controller:
    image: ngrinder/controller:3.5.9-p1
    platform: linux/amd64
    restart: always
    ports:
      - "8300:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent:3.5.9-p1
    platform: linux/amd64
    restart: always
    links:
      - controller
