version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    build: ../../docker_file/nginx
    ports:
      - "9889:80"
    # volumes:
    #  - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - myblog
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  myblog:
    build: ../../docker_file/httpd
    deploy:
      mode: replicated
      replicas: 2 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com,aws.abcdef.com
      - VIRTUAL_PORT=80
