name: awsgoo
services:
  nginx-proxy:
    # build: ../../docker_file/nginx_compose
    image: jiminu/nginx-compose:0.1.0-amd
    ports:
      - "9889:80"

    depends_on:
      - myblog
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M

  scg-proxy:
    # build: ../../../sc-gateway
    image: jiminu/sc-gateway:0.4.0-amd
    ports:
      - "9000:9000"
    depends_on:
      - myblog
      - sc-eureka
    environment:
      - HELLO_SVC_URI=http://awsgoo-myblog-1:8080
        #- EUREKA_SVC_URI=http://sc-eureka:9090
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://sc-eureka:9090/eureka

  myblog:
    image: jiminu/simple-spring:0.1.2-amd
    ports:
      - "8765:8080"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 300M
        reservations:
          cpus: '0.01'
          memory: 20M
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=aws.google.com,aws.abcdef.com
      - VIRTUAL_PORT=8080
      - CPU_STRESS_NUMBER=500
