name: service
services:
  myblog:
    image: jiminu/simple-spring:0.1.2-amd
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 300M
        reservations:
          cpus: '0.01'
          memory: 20M
    environment:
      - VIRTUAL_HOST=aws.google.com,aws.abcdef.com
      - VIRTUAL_PORT=8080
      - CPU_STRESS_NUMBER=500

  user-service:
    build: ./scloud/user-service
      # image: jiminu/user-service:0.1.0-amd
    ports:
      - "9001:9001"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://172.31.9.224:8765/eureka
      - EC2_PRIVATE_IP=172.31.7.234
      - SERVER_PORT=9001
      - CPU_STRESS_NUMBER=500
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_EXAMPLE_USER_SERVICE=DEBUG # 사용자 패키지를 DEBUG로 설정
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG  # Spring Web 관련 로그를 상세히 보고 싶을 때 추가
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 300M
        reservations:
          cpus: '0.01'
          memory: 20M
